# Generated by Django 3.2.15 on 2022-10-01 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20221001_0935'),
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagePublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='publication',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created', to='accounts.profile'),
        ),
        migrations.AddField(
            model_name='publication',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated', to='accounts.profile'),
        ),
        migrations.RemoveField(
            model_name='publication',
            name='photos',
        ),
        migrations.AddField(
            model_name='publication',
            name='photos',
            field=models.ManyToManyField(to='publications.ImagePublication'),
        ),
    ]
