# Generated by Django 3.2.15 on 2022-10-10 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0004_publication_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='is_pro',
            field=models.BooleanField(default=True),
        ),
    ]
