# Generated by Django 3.2.15 on 2022-10-15 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0005_publication_is_pro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='photos',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='publication',
            name='type',
            field=models.CharField(blank=True, choices=[('supply', 'supply'), ('demand', 'demand')], max_length=6, null=True),
        ),
    ]
