# Generated by Django 3.2.15 on 2022-10-15 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0006_auto_20221015_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='photos',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
